name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

    habits:
      runs-on: ubuntu-latest
      steps:
        - uses: lowlighter/metrics@latest
          with:
            filename: github-habits.svg
            token: ${{ secrets.METRICS_TOKEN }}
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            config_timezone: ${{ secrets.USER_TIMEZONE }} # Set timezone
            user: dsubject
            base: ""
            template: classic
            plugin_habits: yes
            plugin_habits_from: 200       # Use 200 events to compute habits
            plugin_habits_days: 14        # Keep only events from last 14 days
            plugin_habits_charts: yes     # Display charts section
            plugin_habits_trim: yes       # Trim unused hours on daily chart
